### ISSUE TITLE
Text clock fullscreen

### ISSUE THREAD

**Issue by airart** [ngnijland/MMM-text-clock#23]
Hi , i love this module , I'm trying to set the module to full screen on a single page, the primary. I would like it to expand based on the rotation of the screen.
it's possible ?

**Comment by ngnijland** [comment]
Hi @airart,

I'm glad you're enjoying the module!

To understand your question better. Do you mean that you want the clock to be "responsive". So the font-size and size of the grid should expand to the available space they have?

**Comment by airart** [comment]
Yes exactly

Filippo Gallerani

**Comment by airart** [comment]
I've a first page in my MM that i use as clock  , then it rotate to other pages  , my pc can rotate from landscape to portrait so clock shuld stretch to full screen to fit ... screen :-)

**Comment by ngnijland** [comment]
Ah, so also stretch out of aspect ratio?

Right now there's only 3 size options that determine the size of the text and the grid.

An option is to add a `stretch` config that makes the module stretch vertically and horizontally to its available space. Then `size` and `stretch` can be used in combination to style the module to preference.

Would that fit your needs? Feel free to submit a PR, I'll review it! Otherwise I'll maybe have some time left next week or the week after to try and implement it!

**Comment by ngnijland** [comment]
Hi @airart ,

I'll probably have time to work on this coming Thursday! So just a double check. Do you want the text clock to stay squared or should it stretch out of aspect ratio?

**Comment by airart** [comment]
Stretch out if is possible 
Tnx

Filippo Gallerani

**Comment by ngnijland** [comment]
@airart I added a `fullscreen` config (pushed it to master already)! Try it out and let me know if it is what you wanted!

See here a preview on my mirror with size medium and large:
![IMG_2308 copy](https://user-images.githubusercontent.com/4727742/124986687-2f3b3100-e03c-11eb-8b7e-30ec16b47f5f.jpg)
![IMG_2309 copy](https://user-images.githubusercontent.com/4727742/124986701-33ffe500-e03c-11eb-8c31-03a0372870b6.jpg)

**Comment by airart** [comment]
Tnx a lot bro ! I’ll try asap this weekend!
Fullscreen overwrite position module? Or i put on fullscreen_below ?

Filippo Gallerani

**Comment by ngnijland** [comment]
Nice! Let me know what you think!

The position doesn't matter. I used position fixed to position the grid. Should overwrite all restrictions setup by magic mirrors position config
